// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GraphResp.proto

#include "GraphResp.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)
class GraphRespDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<GraphResp>
      _instance;
} _GraphResp_default_instance_;
namespace protobuf_GraphResp_2eproto {
void InitDefaultsGraphRespImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  ::google::protobuf::internal::InitProtobufDefaultsForceUnique();
#else
  ::google::protobuf::internal::InitProtobufDefaults();
#endif  // GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  {
    void* ptr = &::_GraphResp_default_instance_;
    new (ptr) ::GraphResp();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::GraphResp::InitAsDefaultInstance();
}

void InitDefaultsGraphResp() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &InitDefaultsGraphRespImpl);
}

::google::protobuf::Metadata file_level_metadata[1];

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::GraphResp, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::GraphResp, resp_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::GraphResp, aggrgate_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::GraphResp, timestamp_),
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::GraphResp)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::_GraphResp_default_instance_),
};

void protobuf_AssignDescriptors() {
  AddDescriptors();
  ::google::protobuf::MessageFactory* factory = NULL;
  AssignDescriptors(
      "GraphResp.proto", schemas, file_default_instances, TableStruct::offsets, factory,
      file_level_metadata, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_PROTOBUF_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 1);
}

void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n\017GraphResp.proto\">\n\tGraphResp\022\014\n\004resp\030\001"
      " \001(\010\022\020\n\010aggrgate\030\002 \001(\001\022\021\n\ttimestamp\030\003 \001("
      "\rb\006proto3"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 89);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "GraphResp.proto", &protobuf_RegisterTypes);
}

void AddDescriptors() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;
}  // namespace protobuf_GraphResp_2eproto

// ===================================================================

void GraphResp::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int GraphResp::kRespFieldNumber;
const int GraphResp::kAggrgateFieldNumber;
const int GraphResp::kTimestampFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

GraphResp::GraphResp()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    ::protobuf_GraphResp_2eproto::InitDefaultsGraphResp();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:GraphResp)
}
GraphResp::GraphResp(const GraphResp& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::memcpy(&aggrgate_, &from.aggrgate_,
    static_cast<size_t>(reinterpret_cast<char*>(&timestamp_) -
    reinterpret_cast<char*>(&aggrgate_)) + sizeof(timestamp_));
  // @@protoc_insertion_point(copy_constructor:GraphResp)
}

void GraphResp::SharedCtor() {
  ::memset(&aggrgate_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&timestamp_) -
      reinterpret_cast<char*>(&aggrgate_)) + sizeof(timestamp_));
  _cached_size_ = 0;
}

GraphResp::~GraphResp() {
  // @@protoc_insertion_point(destructor:GraphResp)
  SharedDtor();
}

void GraphResp::SharedDtor() {
}

void GraphResp::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* GraphResp::descriptor() {
  ::protobuf_GraphResp_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_GraphResp_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const GraphResp& GraphResp::default_instance() {
  ::protobuf_GraphResp_2eproto::InitDefaultsGraphResp();
  return *internal_default_instance();
}

GraphResp* GraphResp::New(::google::protobuf::Arena* arena) const {
  GraphResp* n = new GraphResp;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void GraphResp::Clear() {
// @@protoc_insertion_point(message_clear_start:GraphResp)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&aggrgate_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&timestamp_) -
      reinterpret_cast<char*>(&aggrgate_)) + sizeof(timestamp_));
  _internal_metadata_.Clear();
}

bool GraphResp::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:GraphResp)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // bool resp = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &resp_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // double aggrgate = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(17u /* 17 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &aggrgate_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // uint32 timestamp = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(24u /* 24 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &timestamp_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:GraphResp)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:GraphResp)
  return false;
#undef DO_
}

void GraphResp::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:GraphResp)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // bool resp = 1;
  if (this->resp() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(1, this->resp(), output);
  }

  // double aggrgate = 2;
  if (this->aggrgate() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(2, this->aggrgate(), output);
  }

  // uint32 timestamp = 3;
  if (this->timestamp() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(3, this->timestamp(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:GraphResp)
}

::google::protobuf::uint8* GraphResp::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:GraphResp)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // bool resp = 1;
  if (this->resp() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(1, this->resp(), target);
  }

  // double aggrgate = 2;
  if (this->aggrgate() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(2, this->aggrgate(), target);
  }

  // uint32 timestamp = 3;
  if (this->timestamp() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(3, this->timestamp(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:GraphResp)
  return target;
}

size_t GraphResp::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:GraphResp)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // double aggrgate = 2;
  if (this->aggrgate() != 0) {
    total_size += 1 + 8;
  }

  // bool resp = 1;
  if (this->resp() != 0) {
    total_size += 1 + 1;
  }

  // uint32 timestamp = 3;
  if (this->timestamp() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->timestamp());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void GraphResp::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:GraphResp)
  GOOGLE_DCHECK_NE(&from, this);
  const GraphResp* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const GraphResp>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:GraphResp)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:GraphResp)
    MergeFrom(*source);
  }
}

void GraphResp::MergeFrom(const GraphResp& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:GraphResp)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.aggrgate() != 0) {
    set_aggrgate(from.aggrgate());
  }
  if (from.resp() != 0) {
    set_resp(from.resp());
  }
  if (from.timestamp() != 0) {
    set_timestamp(from.timestamp());
  }
}

void GraphResp::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:GraphResp)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void GraphResp::CopyFrom(const GraphResp& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:GraphResp)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool GraphResp::IsInitialized() const {
  return true;
}

void GraphResp::Swap(GraphResp* other) {
  if (other == this) return;
  InternalSwap(other);
}
void GraphResp::InternalSwap(GraphResp* other) {
  using std::swap;
  swap(aggrgate_, other->aggrgate_);
  swap(resp_, other->resp_);
  swap(timestamp_, other->timestamp_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata GraphResp::GetMetadata() const {
  protobuf_GraphResp_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_GraphResp_2eproto::file_level_metadata[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)

// @@protoc_insertion_point(global_scope)
