// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GraphResp.proto

#ifndef PROTOBUF_GraphResp_2eproto__INCLUDED
#define PROTOBUF_GraphResp_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3005001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace protobuf_GraphResp_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[1];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
void InitDefaultsGraphRespImpl();
void InitDefaultsGraphResp();
inline void InitDefaults() {
  InitDefaultsGraphResp();
}
}  // namespace protobuf_GraphResp_2eproto
class GraphResp;
class GraphRespDefaultTypeInternal;
extern GraphRespDefaultTypeInternal _GraphResp_default_instance_;

// ===================================================================

class GraphResp : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:GraphResp) */ {
 public:
  GraphResp();
  virtual ~GraphResp();

  GraphResp(const GraphResp& from);

  inline GraphResp& operator=(const GraphResp& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  GraphResp(GraphResp&& from) noexcept
    : GraphResp() {
    *this = ::std::move(from);
  }

  inline GraphResp& operator=(GraphResp&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const GraphResp& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const GraphResp* internal_default_instance() {
    return reinterpret_cast<const GraphResp*>(
               &_GraphResp_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    0;

  void Swap(GraphResp* other);
  friend void swap(GraphResp& a, GraphResp& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline GraphResp* New() const PROTOBUF_FINAL { return New(NULL); }

  GraphResp* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const GraphResp& from);
  void MergeFrom(const GraphResp& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(GraphResp* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // double aggrgate = 2;
  void clear_aggrgate();
  static const int kAggrgateFieldNumber = 2;
  double aggrgate() const;
  void set_aggrgate(double value);

  // bool resp = 1;
  void clear_resp();
  static const int kRespFieldNumber = 1;
  bool resp() const;
  void set_resp(bool value);

  // uint32 timestamp = 3;
  void clear_timestamp();
  static const int kTimestampFieldNumber = 3;
  ::google::protobuf::uint32 timestamp() const;
  void set_timestamp(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:GraphResp)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  double aggrgate_;
  bool resp_;
  ::google::protobuf::uint32 timestamp_;
  mutable int _cached_size_;
  friend struct ::protobuf_GraphResp_2eproto::TableStruct;
  friend void ::protobuf_GraphResp_2eproto::InitDefaultsGraphRespImpl();
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// GraphResp

// bool resp = 1;
inline void GraphResp::clear_resp() {
  resp_ = false;
}
inline bool GraphResp::resp() const {
  // @@protoc_insertion_point(field_get:GraphResp.resp)
  return resp_;
}
inline void GraphResp::set_resp(bool value) {
  
  resp_ = value;
  // @@protoc_insertion_point(field_set:GraphResp.resp)
}

// double aggrgate = 2;
inline void GraphResp::clear_aggrgate() {
  aggrgate_ = 0;
}
inline double GraphResp::aggrgate() const {
  // @@protoc_insertion_point(field_get:GraphResp.aggrgate)
  return aggrgate_;
}
inline void GraphResp::set_aggrgate(double value) {
  
  aggrgate_ = value;
  // @@protoc_insertion_point(field_set:GraphResp.aggrgate)
}

// uint32 timestamp = 3;
inline void GraphResp::clear_timestamp() {
  timestamp_ = 0u;
}
inline ::google::protobuf::uint32 GraphResp::timestamp() const {
  // @@protoc_insertion_point(field_get:GraphResp.timestamp)
  return timestamp_;
}
inline void GraphResp::set_timestamp(::google::protobuf::uint32 value) {
  
  timestamp_ = value;
  // @@protoc_insertion_point(field_set:GraphResp.timestamp)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_GraphResp_2eproto__INCLUDED
