// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GraphMessage.proto

#ifndef PROTOBUF_GraphMessage_2eproto__INCLUDED
#define PROTOBUF_GraphMessage_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3005001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace protobuf_GraphMessage_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[1];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
void InitDefaultsGraphMessageImpl();
void InitDefaultsGraphMessage();
inline void InitDefaults() {
  InitDefaultsGraphMessage();
}
}  // namespace protobuf_GraphMessage_2eproto
class GraphMessage;
class GraphMessageDefaultTypeInternal;
extern GraphMessageDefaultTypeInternal _GraphMessage_default_instance_;

// ===================================================================

class GraphMessage : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:GraphMessage) */ {
 public:
  GraphMessage();
  virtual ~GraphMessage();

  GraphMessage(const GraphMessage& from);

  inline GraphMessage& operator=(const GraphMessage& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  GraphMessage(GraphMessage&& from) noexcept
    : GraphMessage() {
    *this = ::std::move(from);
  }

  inline GraphMessage& operator=(GraphMessage&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const GraphMessage& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const GraphMessage* internal_default_instance() {
    return reinterpret_cast<const GraphMessage*>(
               &_GraphMessage_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    0;

  void Swap(GraphMessage* other);
  friend void swap(GraphMessage& a, GraphMessage& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline GraphMessage* New() const PROTOBUF_FINAL { return New(NULL); }

  GraphMessage* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const GraphMessage& from);
  void MergeFrom(const GraphMessage& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(GraphMessage* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // int64 sourceId = 1;
  void clear_sourceid();
  static const int kSourceIdFieldNumber = 1;
  ::google::protobuf::int64 sourceid() const;
  void set_sourceid(::google::protobuf::int64 value);

  // int64 targetId = 2;
  void clear_targetid();
  static const int kTargetIdFieldNumber = 2;
  ::google::protobuf::int64 targetid() const;
  void set_targetid(::google::protobuf::int64 value);

  // double value = 3;
  void clear_value();
  static const int kValueFieldNumber = 3;
  double value() const;
  void set_value(double value);

  // @@protoc_insertion_point(class_scope:GraphMessage)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::int64 sourceid_;
  ::google::protobuf::int64 targetid_;
  double value_;
  mutable int _cached_size_;
  friend struct ::protobuf_GraphMessage_2eproto::TableStruct;
  friend void ::protobuf_GraphMessage_2eproto::InitDefaultsGraphMessageImpl();
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// GraphMessage

// int64 sourceId = 1;
inline void GraphMessage::clear_sourceid() {
  sourceid_ = GOOGLE_LONGLONG(0);
}
inline ::google::protobuf::int64 GraphMessage::sourceid() const {
  // @@protoc_insertion_point(field_get:GraphMessage.sourceId)
  return sourceid_;
}
inline void GraphMessage::set_sourceid(::google::protobuf::int64 value) {
  
  sourceid_ = value;
  // @@protoc_insertion_point(field_set:GraphMessage.sourceId)
}

// int64 targetId = 2;
inline void GraphMessage::clear_targetid() {
  targetid_ = GOOGLE_LONGLONG(0);
}
inline ::google::protobuf::int64 GraphMessage::targetid() const {
  // @@protoc_insertion_point(field_get:GraphMessage.targetId)
  return targetid_;
}
inline void GraphMessage::set_targetid(::google::protobuf::int64 value) {
  
  targetid_ = value;
  // @@protoc_insertion_point(field_set:GraphMessage.targetId)
}

// double value = 3;
inline void GraphMessage::clear_value() {
  value_ = 0;
}
inline double GraphMessage::value() const {
  // @@protoc_insertion_point(field_get:GraphMessage.value)
  return value_;
}
inline void GraphMessage::set_value(double value) {
  
  value_ = value;
  // @@protoc_insertion_point(field_set:GraphMessage.value)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_GraphMessage_2eproto__INCLUDED
