// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PSResponse.proto

#ifndef PROTOBUF_PSResponse_2eproto__INCLUDED
#define PROTOBUF_PSResponse_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3005001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace protobuf_PSResponse_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[1];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
void InitDefaultsPSResponseImpl();
void InitDefaultsPSResponse();
inline void InitDefaults() {
  InitDefaultsPSResponse();
}
}  // namespace protobuf_PSResponse_2eproto
class PSResponse;
class PSResponseDefaultTypeInternal;
extern PSResponseDefaultTypeInternal _PSResponse_default_instance_;

// ===================================================================

class PSResponse : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:PSResponse) */ {
 public:
  PSResponse();
  virtual ~PSResponse();

  PSResponse(const PSResponse& from);

  inline PSResponse& operator=(const PSResponse& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  PSResponse(PSResponse&& from) noexcept
    : PSResponse() {
    *this = ::std::move(from);
  }

  inline PSResponse& operator=(PSResponse&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const PSResponse& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const PSResponse* internal_default_instance() {
    return reinterpret_cast<const PSResponse*>(
               &_PSResponse_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    0;

  void Swap(PSResponse* other);
  friend void swap(PSResponse& a, PSResponse& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline PSResponse* New() const PROTOBUF_FINAL { return New(NULL); }

  PSResponse* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const PSResponse& from);
  void MergeFrom(const PSResponse& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(PSResponse* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated uint64 keys = 2;
  int keys_size() const;
  void clear_keys();
  static const int kKeysFieldNumber = 2;
  ::google::protobuf::uint64 keys(int index) const;
  void set_keys(int index, ::google::protobuf::uint64 value);
  void add_keys(::google::protobuf::uint64 value);
  const ::google::protobuf::RepeatedField< ::google::protobuf::uint64 >&
      keys() const;
  ::google::protobuf::RepeatedField< ::google::protobuf::uint64 >*
      mutable_keys();

  // repeated double vals = 3;
  int vals_size() const;
  void clear_vals();
  static const int kValsFieldNumber = 3;
  double vals(int index) const;
  void set_vals(int index, double value);
  void add_vals(double value);
  const ::google::protobuf::RepeatedField< double >&
      vals() const;
  ::google::protobuf::RepeatedField< double >*
      mutable_vals();

  // bool resp = 1;
  void clear_resp();
  static const int kRespFieldNumber = 1;
  bool resp() const;
  void set_resp(bool value);

  // uint32 timestamp = 4;
  void clear_timestamp();
  static const int kTimestampFieldNumber = 4;
  ::google::protobuf::uint32 timestamp() const;
  void set_timestamp(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:PSResponse)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedField< ::google::protobuf::uint64 > keys_;
  mutable int _keys_cached_byte_size_;
  ::google::protobuf::RepeatedField< double > vals_;
  mutable int _vals_cached_byte_size_;
  bool resp_;
  ::google::protobuf::uint32 timestamp_;
  mutable int _cached_size_;
  friend struct ::protobuf_PSResponse_2eproto::TableStruct;
  friend void ::protobuf_PSResponse_2eproto::InitDefaultsPSResponseImpl();
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// PSResponse

// bool resp = 1;
inline void PSResponse::clear_resp() {
  resp_ = false;
}
inline bool PSResponse::resp() const {
  // @@protoc_insertion_point(field_get:PSResponse.resp)
  return resp_;
}
inline void PSResponse::set_resp(bool value) {
  
  resp_ = value;
  // @@protoc_insertion_point(field_set:PSResponse.resp)
}

// repeated uint64 keys = 2;
inline int PSResponse::keys_size() const {
  return keys_.size();
}
inline void PSResponse::clear_keys() {
  keys_.Clear();
}
inline ::google::protobuf::uint64 PSResponse::keys(int index) const {
  // @@protoc_insertion_point(field_get:PSResponse.keys)
  return keys_.Get(index);
}
inline void PSResponse::set_keys(int index, ::google::protobuf::uint64 value) {
  keys_.Set(index, value);
  // @@protoc_insertion_point(field_set:PSResponse.keys)
}
inline void PSResponse::add_keys(::google::protobuf::uint64 value) {
  keys_.Add(value);
  // @@protoc_insertion_point(field_add:PSResponse.keys)
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::uint64 >&
PSResponse::keys() const {
  // @@protoc_insertion_point(field_list:PSResponse.keys)
  return keys_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::uint64 >*
PSResponse::mutable_keys() {
  // @@protoc_insertion_point(field_mutable_list:PSResponse.keys)
  return &keys_;
}

// repeated double vals = 3;
inline int PSResponse::vals_size() const {
  return vals_.size();
}
inline void PSResponse::clear_vals() {
  vals_.Clear();
}
inline double PSResponse::vals(int index) const {
  // @@protoc_insertion_point(field_get:PSResponse.vals)
  return vals_.Get(index);
}
inline void PSResponse::set_vals(int index, double value) {
  vals_.Set(index, value);
  // @@protoc_insertion_point(field_set:PSResponse.vals)
}
inline void PSResponse::add_vals(double value) {
  vals_.Add(value);
  // @@protoc_insertion_point(field_add:PSResponse.vals)
}
inline const ::google::protobuf::RepeatedField< double >&
PSResponse::vals() const {
  // @@protoc_insertion_point(field_list:PSResponse.vals)
  return vals_;
}
inline ::google::protobuf::RepeatedField< double >*
PSResponse::mutable_vals() {
  // @@protoc_insertion_point(field_mutable_list:PSResponse.vals)
  return &vals_;
}

// uint32 timestamp = 4;
inline void PSResponse::clear_timestamp() {
  timestamp_ = 0u;
}
inline ::google::protobuf::uint32 PSResponse::timestamp() const {
  // @@protoc_insertion_point(field_get:PSResponse.timestamp)
  return timestamp_;
}
inline void PSResponse::set_timestamp(::google::protobuf::uint32 value) {
  
  timestamp_ = value;
  // @@protoc_insertion_point(field_set:PSResponse.timestamp)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_PSResponse_2eproto__INCLUDED
