// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RegisterMessage.proto

#ifndef PROTOBUF_RegisterMessage_2eproto__INCLUDED
#define PROTOBUF_RegisterMessage_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3005001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace protobuf_RegisterMessage_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[1];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
void InitDefaultsRegisterMessageImpl();
void InitDefaultsRegisterMessage();
inline void InitDefaults() {
  InitDefaultsRegisterMessage();
}
}  // namespace protobuf_RegisterMessage_2eproto
class RegisterMessage;
class RegisterMessageDefaultTypeInternal;
extern RegisterMessageDefaultTypeInternal _RegisterMessage_default_instance_;

// ===================================================================

class RegisterMessage : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:RegisterMessage) */ {
 public:
  RegisterMessage();
  virtual ~RegisterMessage();

  RegisterMessage(const RegisterMessage& from);

  inline RegisterMessage& operator=(const RegisterMessage& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  RegisterMessage(RegisterMessage&& from) noexcept
    : RegisterMessage() {
    *this = ::std::move(from);
  }

  inline RegisterMessage& operator=(RegisterMessage&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const RegisterMessage& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const RegisterMessage* internal_default_instance() {
    return reinterpret_cast<const RegisterMessage*>(
               &_RegisterMessage_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    0;

  void Swap(RegisterMessage* other);
  friend void swap(RegisterMessage& a, RegisterMessage& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline RegisterMessage* New() const PROTOBUF_FINAL { return New(NULL); }

  RegisterMessage* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const RegisterMessage& from);
  void MergeFrom(const RegisterMessage& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(RegisterMessage* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // int32 machineId = 1;
  void clear_machineid();
  static const int kMachineIdFieldNumber = 1;
  ::google::protobuf::int32 machineid() const;
  void set_machineid(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:RegisterMessage)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::int32 machineid_;
  mutable int _cached_size_;
  friend struct ::protobuf_RegisterMessage_2eproto::TableStruct;
  friend void ::protobuf_RegisterMessage_2eproto::InitDefaultsRegisterMessageImpl();
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// RegisterMessage

// int32 machineId = 1;
inline void RegisterMessage::clear_machineid() {
  machineid_ = 0;
}
inline ::google::protobuf::int32 RegisterMessage::machineid() const {
  // @@protoc_insertion_point(field_get:RegisterMessage.machineId)
  return machineid_;
}
inline void RegisterMessage::set_machineid(::google::protobuf::int32 value) {
  
  machineid_ = value;
  // @@protoc_insertion_point(field_set:RegisterMessage.machineId)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_RegisterMessage_2eproto__INCLUDED
